# permissions for end users to view todoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: todo-viewer-role
rules:
- apiGroups:
  - todo.johnliu55.tw
  resources:
  - todoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - todo.johnliu55.tw
  resources:
  - todoes/status
  verbs:
  - get
