apiVersion: todo.johnliu55.tw/v1
kind: Todo
metadata:
  name: todo-sample
spec:
  # Add fields here
  summary: "Buy some milk"
  complete: false
  notifyEmail: "john.liu@suse.com"
  notifyAt: "2021-09-13T14:00:00+08:00"
